# Generated by Django 6.0 on 2025-12-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
    ]
