# Generated by Django 6.0 on 2025-12-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_messages", "0001_initial"),
        ("mail_recipients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылок"},
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="stat_time",
            new_name="start_time",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                related_name="mailing", to="mail_recipients.custommailrecipient", verbose_name="Получатели"
            ),
        ),
    ]
