# Generated by Django 6.0 on 2025-12-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_messages", "0002_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                    ("failed", "Ошибка"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
