# Generated by Django 6.0 on 2025-12-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_messages", "0003_mailing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_moderated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("on_moderation", "На модерации"),
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                    ("failed", "Ошибка"),
                ],
                default="on_moderation",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
