# Generated by Django 6.0 on 2025-12-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_messages", "0004_mailing_is_moderated_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="custommessage",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
    ]
