# Generated by Django 6.0 on 2025-12-23 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_messages", "0005_alter_custommessage_options_alter_mailing_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="custommessage",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Сообщение",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailing",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер клиента рассылки",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="custommessage",
            unique_together={("theme_mail", "owner")},
        ),
        migrations.AlterUniqueTogether(
            name="mailing",
            unique_together={("message", "owner")},
        ),
    ]
