# Generated by Django 6.0 on 2026-01-01 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_messages", "0007_alter_custommessage_options_alter_mailing_options_and_more"),
        ("mail_recipients", "0004_alter_custommailrecipient_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "Успешно"), ("failed", "Ошибка")],
                        max_length=20,
                        verbose_name="Статус отправки",
                    ),
                ),
                ("is_sending", models.BooleanField(blank=True, null=True)),
                ("attempt_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mailing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing",
                        to="mail_messages.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
                (
                    "recipients",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing_recipients",
                        to="mail_recipients.custommailrecipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка отправки рассылки",
                "verbose_name_plural": "Попытки отправки рассылок",
            },
        ),
    ]
