# Generated by Django 6.0 on 2026-01-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_messages", "0008_mailingattempt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["-attempt_time"],
                "verbose_name": "Попытка отправки рассылки",
                "verbose_name_plural": "Попытки отправки рассылок",
            },
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="details",
            field=models.TextField(blank=True, null=True, verbose_name="Детали отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("on_moderation", "На модерации"),
                    ("created", "Создана"),
                    ("started", "Готова к отправке"),
                    ("completed", "Завершена"),
                    ("failed", "Ошибка"),
                ],
                default="on_moderation",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="attempt_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
