# Generated by Django 6.0 on 2025-12-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomMailRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Адрес электронной почты")),
                ("first_name", models.CharField(max_length=50, null=True, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, null=True, verbose_name="Фамилия")),
                ("middle_name", models.CharField(max_length=50, null=True, verbose_name="Отчество")),
                ("description", models.TextField(verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
