# Generated by Django 6.0 on 2025-12-23 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_recipients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="custommailrecipient",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер клиента рассылки",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="custommailrecipient",
            unique_together={("email", "owner")},
        ),
    ]
