# Generated by Django 6.0 on 2025-12-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_recipients", "0003_alter_custommailrecipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="custommailrecipient",
            options={
                "permissions": [("can_view_recipient", "Can view recipient")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
